### ISSUE TITLE
underscore sign in snippet codes 4.19 & 4.20

### ISSUE THREAD

**Issue by tagomatech** [ksachdeva/rethinking-tensorflow-probability#1]
Thank you for this repository @ksachdeva and apologies as I'm not really escalating any "issue". I just have a question for you but don't know how to contact you by any other mean.

Your snippet code `4.19 & 4.20` reads:
`sample_rows = tfd.Categorical(probs=(joint_prob/tf.reduce_sum(joint_prob))).sample(10_000)`

For some reason (I looked into `tfp` code but it remains quite obscure to me to be honest), one can actually insert (only) one underscore sign in between 2 digits of the `sample_shape` argument of the `sample()` method (e.g.  1_0_0, 100_0, etc... would work just fine).

I want to ask you, in the context of your snippet code `4.19 & 4.20` specifically , what is the purpose of using underscore? Do you merely use it as thousand separator?

Thank you.

**Comment by ksachdeva** [comment]
Hi @tagomatech 

> Do you merely use it as a thousand separator?

This is the only purpose. 

But it is not something related to tfp. This is supported by the python language. Using underscores potentially helps in reading a bigger number easier.

More details here - https://www.python.org/dev/peps/pep-0515/

Regards
Kapil

**Comment by tagomatech** [comment]
Hi  @ksachdeva thank you for kindly answering.
Thank you for the PEP.
I have never heard of this underscore trick before.
Thank you for teaching me something new.
